[package]
name = "satellites_native"
version = "0.1.0"
edition = "2021"

[lib]
name = "satellites_native"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }

